#!/bin/sh -e

export LC_ALL=C

[ $# -eq 2 ] || exit 0

PATH=/usr/sbin:/sbin:$PATH

. /usr/libexec/ddns-update/functions

# Run the right scripts
case "$2" in
    up|vpn-up|dhcp4-change)
    	if [ "$1" == "$IF" ]; then
            logger -s "ddns-update NetworkManager-dispatcher up $IF"
            discover_update
	    fi
    ;;
esac

exit 0